[package]
name = "rare-updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"
reqwest = { version = "0.11.11", features = ["blocking"] }